# This file build the release version of the app, currently, for android only.
name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Flutter Actions
      uses: subosito/flutter-action@v2
      with: 
        flutter-version: '3.13.9'

    - name: Install Dependencies
      run: flutter pub get

    - name: Build and Test
      run: flutter build apk --release 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Upload Release APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk
